config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-platinum-whale.sh
        container: qc.acc_woozy-olive-crab
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cardinal-javanese.sh
        container: qc.doc_ugly-tomato-bullfrog
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-dandelion-akbash.sh
        container: qc.doc_fuzzy-pear-labradoodle
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-smalt-lion.sh
        container: qc.doc_hasty-aqua-liger
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-razzmatazz-javanese.sh
        container: qc.lic_baggy-crimson-sloth
  QC.Sec:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cerulean-spitz.sh
        container: qc.sec_blurry-ecru-bee
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-brown-mist.sh
        container: qc.sty_lanky-rust-pinscher
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-lizard.sh
        container: qc.sty_hazy-violet-hyrax
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cobalt-heron.sh
        container: qc.sty_skanky-coral-caterpillar
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-gold-kangaroo.sh
        container: qc.ver_slaphappy-olivine-spitz
timeout: 5400
