config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-alizarin-paradise.sh
        container: qc.acc_clammy-olive-wolfhound
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cinnabar-okapi.sh
        container: qc.doc_flaky-cerulean-weasel
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-maroon-newt.sh
        container: qc.doc_stealthy-wheat-macaque
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-goldenrod-fowl.sh
        container: qc.doc_seedy-ruby-bordeaux
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-jade-deer.sh
        container: qc.lic_whiny-olivine-leopard
  QC.Sec:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-violet-ibis.sh
        container: qc.sec_lousy-silver-capuchin
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cobalt-retriever.sh
        container: qc.sty_cloudy-brass-butterfly
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-carmine-magpie.sh
        container: qc.sty_flabby-apricot-peccary
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-heliotrope-lynx.sh
        container: qc.sty_woozy-silver-llama
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-taupe-cougar.sh
        container: qc.ver_homely-malachite-kakapo
timeout: 5400
